services:
  accounts:
    image: "ysurendrareddy333/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sj

  loans:
    image: "ysurendrareddy333/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sj

  cards:
    image: "ysurendrareddy333/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sj

networks:
  sj:
    driver: bridge
